---
title: "[XSTSF] Tone sandhi patterns for trisyllabic LML-X tokens"
output: html_document
author: Yibing Shi
date: "Last updated: 2023-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(plotly)
library(writexl)
library(readxl)
```


## Citation sandhi  

### Data frame construction  

```{r data-construction}
## all tokens
f0_tri_ct <- f0_all %>%
  filter(focus_condition == 'citation' & diortri == 'tri')


## HH-x tokens starting with yin-ping
# check citation_no for each token
#   distinct(f0_tri_ct_1, token, citation_no)
# 16 tokens: [1]新书包42，采樱花33，修车工36，青椒籽38
#            [2]新书房19，采樱桃40，开锁人43，青椒皮44
#            [3]新皮袄5，采梅花3，修门工7，樱桃籽9，
#            [4]新皮鞋14，采杨梅15，开门人21，樱桃皮23，
#            [5]老青椒2，买青椒4，造纸厂6，黄瓜籽11
#            [6]老樱桃13，买樱桃24，买花人22，黄瓜皮20
#            [7]老黄瓜16，买黄瓜18，造船厂28，杨梅籽30
#            [8]老杨梅8，买杨梅32，买茶人41，杨桃皮26
            # numbers indicating citation_no
# 8 speakers * 16 tokens *  10 normalised time points * 3 syllables = 3840 
f0_tri_ct_1 <- f0_tri_ct %>%
  filter(!str_starts(token, '小|苦|新手'))

kable(f0_tri_ct_1) %>%
  kable_styling("striped", full_width = F) %>%
  scroll_box(width = "100%", height = "300px")


# check syntax categories
#   unique(f0_tri_ct$syntax)


## 2+1 VO+L LML-X 
# 4 tokens: 造纸厂6，买花人22，造船厂28，买茶人41
# 8 speakers * 4 tokens *  10 normalised time points * 3 syllables = 960
f0_tri_lhl_21vl_ct <- f0_tri_ct_1 %>%
  filter(syntax == '2+1VL' & str_starts(citation_tone, 'RF|LH'))
# check citation_no
#   unique(f0_tri_lml_21vl_ct$citation_no)


## 2+1 L+L LML-X 
# 4 tokens: 黄瓜籽11，黄瓜皮20，杨梅籽30，杨桃皮26
# 8 speakers * 4 tokens *  10 normalised time points * 3 syllables = 960
f0_tri_lhl_21ll_ct <- f0_tri_ct_1 %>%
  filter(syntax == '2+1LL' & str_starts(citation_tone, 'RF|LH'))
# check citation_no
#   unique(f0_tri_lml_21ll_ct$citation_no)
```

<br>
<br>

### Data visualisation  
 
**Tokens starting with *yin-ping***
```{r data-visualisation-ind, fig.show='hold', out.width='25%', warning=FALSE}
# prepare the order of the image presentation
f0_tri_ct_1$citation_no <- factor(f0_tri_ct_1$citation_no, levels = c(42, 33, 36, 38, 19, 40, 43, 44, 5, 3, 7, 9, 14, 15, 21, 23, 2, 4, 6, 11, 13, 24, 22, 20, 16, 18, 28, 30, 8, 32, 41, 26))
f0_tri_ct_1 <- f0_tri_ct_1[order(f0_tri_ct_1$citation_no), ]

# visualisation
for (val in unique(f0_tri_ct_1$citation_no)) {
  if (!is.na(val)) print(f0_draw_ind(f0_tri_ct_1, val, 'citation_no'))
}
```


**2+1 VO+L LML-X sandhi**
```{r data-visualisation-21vl-di, fig.show='hold', out.width='50%', warning=FALSE}
# check disyllabic sandhi
# 6 tokens: 买花36，造纸24，买布4，买茶32，造船46，买饭22
# for (val in unique(f0_di_lml_v_ct$citation_tone)) {
#   plot <- f0_draw_group(f0_di_lml_v_ct, val, 'sandhi_tone_final')
#   print(ggplotly(plot))
# }
```

```{r data-visualisation-21vl-ind, fig.show='hold', out.width='50%', warning=FALSE}
## 2+1 VO+L LML-X 
# 4 tokens: 造纸厂6，买花人22，造船厂28，买茶人41
for (val in unique(f0_tri_lhl_21vl_ct$citation_no)) {
  plot <- f0_draw_ind(f0_tri_lhl_21vl_ct, val, 'citation_no')
  print(ggplotly(plot))
}
```


```{r data-visualisation-21vl-group, fig.show='hold', out.width='50%', warning=FALSE}
# import sandhi labeling
f0_tri_lhl_21vl_ct_sandhi <- read_excel('raw_data/tri_sandhi.xlsx', sheet = 'lhl_21vl')
f0_tri_lhl_21vl_ct <- f0_tri_lhl_21vl_ct %>%
  select(-sandhi_tone) %>%
  left_join(f0_tri_lhl_21vl_ct_sandhi[, c('sandhi_tone', 'ind_no')], by = 'ind_no')

f0_tri_lhl_21vl_ct <- f0_tri_lhl_21vl_ct %>%
  mutate(citation_tone_initial = citation_tone) %>%
  mutate(across('citation_tone', str_replace, '^LH|^RF', 'LT'))

# visualisation
for (val in unique(f0_tri_lhl_21vl_ct$citation_tone)) {
  plot <- f0_tri_lhl_21vl_ct %>%
  filter(citation_tone == val) %>%
  ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+ 
  geom_line()+
  facet_wrap(~sandhi_tone)+
  labs(title = paste(val, 'individuals', sep = '_'))+
  ylim(-2.5, 2.5)
  print(ggplotly(plot))
}
```

```{r data-visualisation-21vl-group-2, fig.show='hold', out.width='50%', warning=FALSE}
# import final sandhi labels
f0_tri_lhl_21vl_ct_sandhi <- read_excel('raw_data/tri_sandhi.xlsx', sheet = 'lhl_21vl')
f0_tri_lhl_21vl_ct <- f0_tri_lhl_21vl_ct %>%
  # select(-sandhi_tone_final) %>%
  left_join(f0_tri_lhl_21vl_ct_sandhi[, c('sandhi_tone_final', 'ind_no')], by = 'ind_no')

f0_tri_lhl_21vl_ct <- f0_tri_lhl_21vl_ct %>%
  mutate(across('citation_tone', str_replace, 'LTHHHH|LTHHRF', 'LTHHXX')) %>%
  mutate(across('citation_tone', str_replace, 'LTRFHH|LTRFRF', 'LTRFXX')) 

# visualisation by citation tone
for (val in unique(f0_tri_lhl_21vl_ct$citation_tone)) {
  plot <- f0_tri_lhl_21vl_ct %>%
  filter(citation_tone == val) %>%
  ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+ 
  geom_line()+
  facet_wrap(~sandhi_tone_final)+
  labs(title = paste(val, 'individuals', sep = '_'))+
  ylim(-2.5, 2.5)
  print(ggplotly(plot))
}
```

```{r data-visualisation-21vl-final, fig.show='hold', out.width='50%', warning=FALSE}
# calculate average contours
f0_tri_lhl_21vl_ct_mean <- f0_tri_lhl_21vl_ct %>%
  group_by(citation_tone, sandhi_tone_final, time) %>%
  mutate(mean_f0 = mean(norm_f0), se = se(norm_f0)) %>%
  ungroup() %>%
  # drop out contours that only occur once & abnormal values
  filter(is.na(se) == FALSE) %>%
  # add count label
  group_by(citation_tone, sandhi_tone_final) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  mutate(count_text = ifelse(time == 30, paste('n=', as.character(count/30), sep = ''), NA))
  

# visualisation 
for (val in unique(f0_tri_lhl_21vl_ct_mean$citation_tone)) {
  print(f0_tri_lhl_21vl_ct_mean %>%
  filter(citation_tone == val) %>%
  ggplot(aes(x = factor(time), y = mean_f0, color = sandhi_tone_final, group = interaction(syllable_no, sandhi_tone_final))) +
  geom_errorbar(aes(ymin=mean_f0-se, ymax=mean_f0+se, width=.1))+
  geom_line()+
  geom_point()+
  ylim(-3, 3)+
  labs(title ='')+
  geom_text(aes(label = count_text), vjust = 0, nudge_y = 0.3))
}

unique(f0_tri_lhl_21vl_ct_mean$sandhi_tone_final)
```

**2+1 L+L LML-X sandhi**  
```{r data-visualisation-21ll-ind, fig.show='hold', out.width='50%', warning=FALSE}
### 2+1 L+L LML-X 
# 4 tokens: 黄瓜籽11，黄瓜皮20，杨梅籽30，杨桃皮26

## Visualisation of contours for each token
for (val in unique(f0_tri_lhl_21ll_ct$citation_no)) {
  plot <- f0_draw_ind(f0_tri_lhl_21ll_ct, val, 'citation_no')
  print(ggplotly(plot))
}
```


```{r data-visualisation-21ll-group-1, fig.show='hold', out.width='50%', warning=FALSE}
## Visualisation of contours by sandhi categories

# import initial sandhi labels
f0_tri_lhl_21ll_ct_sandhi <- read_excel('raw_data/tri_sandhi.xlsx', sheet = 'lhl_21ll')
f0_tri_lhl_21ll_ct <- f0_tri_lhl_21ll_ct %>%
  select(-sandhi_tone) %>%
  left_join(f0_tri_lhl_21ll_ct_sandhi[, c('sandhi_tone', 'ind_no')], by = 'ind_no')

# check no. of citation tone combinations
#   unique(f0_tri_lhl_21ll_ct$citation_tone)
f0_tri_lhl_21ll_ct <- f0_tri_lhl_21ll_ct %>%
  mutate(citation_tone_initial = citation_tone) %>%
  mutate(across('citation_tone', str_replace, '^RFHL|^RFHH', 'RFHT')) %>%
  mutate(across('citation_tone', str_replace, '^RFLH|^RFRF', 'RFLT'))

# visualisation
for (val in unique(f0_tri_lhl_21ll_ct$citation_tone)) {
  plot <- f0_tri_lhl_21ll_ct %>%
  filter(citation_tone == val) %>%
  ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+ 
  geom_line()+
  facet_wrap(~sandhi_tone)+
  labs(title = paste(val, 'individuals', sep = '_'))+
  ylim(-2.5, 2.5)
  print(ggplotly(plot))
}
```


```{r data-visualisation-21ll-group-2, fig.show='hold', out.width='50%', warning=FALSE}
# import final sandhi labels
f0_tri_lhl_21ll_ct_sandhi <- read_excel('raw_data/tri_sandhi.xlsx', sheet = 'lhl_21ll')
f0_tri_lhl_21ll_ct <- f0_tri_lhl_21ll_ct %>%
  left_join(f0_tri_lhl_21ll_ct_sandhi[, c('sandhi_tone_final', 'ind_no')], by = 'ind_no')

# visualisation by citation tone
for (val in unique(f0_tri_lhl_21ll_ct$citation_tone)) {
  plot <- f0_tri_lhl_21ll_ct %>%
  filter(citation_tone == val) %>%
  ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+ 
  geom_line()+
  facet_wrap(~sandhi_tone_final)+
  labs(title = paste(val, 'individuals', sep = '_'))+
  ylim(-2.5, 2.5)
  print(ggplotly(plot))
}
```

```{r data-visualisation-21ll-final, fig.show='hold', out.width='50%', warning=FALSE}
# calculate average contours
f0_tri_lhl_21ll_ct_mean <- f0_tri_lhl_21ll_ct %>%
  group_by(sandhi_tone_final, time) %>%
  mutate(mean_f0 = mean(norm_f0), se = se(norm_f0)) %>%
  ungroup() %>%
  # drop out contours that only occur once & abnormal values
  filter(is.na(se) == FALSE) %>%
  # add count label
  group_by(sandhi_tone_final) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  mutate(count_text = ifelse(time == 30, paste('n=', as.character(count/30), sep = ''), NA))
  
# visualisation 
plot_tri_lhl_21ll_ct <- f0_tri_lhl_21ll_ct_mean %>%
  filter(!sandhi_tone_final == 'LLLLHH') %>%
  ggplot(aes(x = factor(time), y = mean_f0, color = sandhi_tone_final, group = interaction(syllable_no, sandhi_tone_final))) +
  geom_errorbar(aes(ymin=mean_f0-se, ymax=mean_f0+se, width=.1))+
  geom_line()+
  geom_point()+
  ylim(-3, 3)+
  labs(title ='')+
  geom_text(aes(label = count_text), vjust = 0, nudge_y = 0.3)

plot_tri_lhl_21ll_ct
```

# Saving
```{r}
save.image('XSTSF_production.RData')
```

